[package]
name = "cellang"
version.workspace = true
edition.workspace = true
license.workspace = true
authors = ["Nikola Jokic <jokicnikola07@gmail.com>"]
description = "Interpreter for the CEL expression language"
repository = "https://github.com/nikola-jokic/cellang"
readme = "README.md"
keywords = ["cel", "expression", "language", "interpreter", "rust"]
categories = ["development-tools", "compilers"]

[dependencies]
serde = { version = "^1", features = ["derive"] }
miette = { version = "^7" }
regex = "^1"
time = { version = "^0.3", features = ["serde", "formatting", "parsing"] }
base64 = "^0.22"
thiserror = "^2"

[dev-dependencies]
miette = { version = "^7", features = ["fancy"] }
serde_json = "^1"
time = { version = "^0.3", features = [
    "serde",
    "formatting",
    "parsing",
    "macros",
] }
